server:
  port: 8082

spring:
  application:
    name: payment-service

logging:
  level:
    root: INFO
    com.twopc: DEBUG
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%-5level] [%logger{36}] - %msg%n"

payment:
  wal:
    base-dir: ./logs

  accounts:
    - customerId: CUST-001
      name: John Doe
      balance: 5000.00
    - customerId: CUST-002
      name: Jane Smith
      balance: 10000.00
    - customerId: CUST-003
      name: Bob Johnson
      balance: 2000.00
    - customerId: CUST-004
      name: Alice Williams
      balance: 15000.00
    - customerId: CUST-005
      name: Charlie Brown
      balance: 500.00